version: '3.8'
services:
  # nginx-server:
  #   image: nginx:1.17.10-alpine
  #   ports: 
  #     - "80:80"
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./client/build:/usr/share/nginx/
  mongodb:
    image: mongo:4.4-bionic
    env_file: ./.env
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  server:
    image: backend-prod
    restart: unless-stopped
    depends_on:
      - mongodb
    build:
      context: ./server
      dockerfile: Dockerfile-prod
    env_file: ./.env
    volumes:
      - ./server:/server
      - /app/node_modules      
    ports:
      - "6868:80"
    networks:
      - docker-app-prod              
  client:
    image: frontend-prod
    depends_on:
      - server    
    build:
      context: ./client
      dockerfile: Dockerfile-prod
    env_file: 
      - ./.env       
    volumes:
      - ./client:/server
      - /app/node_modules 
      - ./client:/usr/share/nginx/html
      - ./client/nginx/nginx.conf:/etc/nginx/nginx.config      
    stdin_open: true
    ports:
      - "8888:8080"
    restart: unless-stopped    
    networks:
      - docker-app-prod             
networks:
  docker-app-prod:
    driver: bridge
volumes:
  db:
    driver: local